### ISSUE TITLE
Unable to export records

### ISSUE THREAD

**Issue by jjdeclercq** [vubiostat/redcapAPI#290] opened 2023-12-15 18:25 UTC
After establishing my redcap connection using `unlockREDCap` I am unable to export records using either `exportRecordsTyped` or `exportRecords`. I'm using package version 2.8.0. 

Here is the output from the error messages I'm receiving:

`redcapAPI::exportRecordsTyped(rcon = anticancer_key)`

```
Error in if (trimws(as.character(response)) == "") { : 
  missing value where TRUE/FALSE needed
```

`redcapAPI::exportRecords(rcon = anticancer_key, factors = TRUE, checkboxLabels = TRUE)`

```
Warning: not all columns named in 'colClasses' existWarning: Missing field for suffix record_idWarning: Missing field for suffix mrn
```
The warning message here seems to repeat for every variable in the data dictionary.

Also, since I'm being encouraged to convert to `exportRecordsTyped`, how can I get the checkbox output to mimic the settings from `factors = TRUE, checkboxLabels = TRUE`?

**Comment by nutterb** [comment] 2023-12-16 23:08
@jjdeclercq , this is kind of an odd error, so I'll ask for your help in trying to work out what's happening. I'd like you to run the following code and report back what the result is. (you don't need to post the data. Mostly what we need to know is if this also returns `NA`). 

You might also try updating to our most recent stable version (2.8.3) using `devtools::install_github("vubiostat/redcapAPI")`. I'm not optimistic that this will do much though, since that line of code hasn't changed in the interim. 


For your last question, you get the same output of `factors = TRUE, checkboxLabels = TRUE`, you can use 

`exportRecordsTyped(rcon = anticancer_key, cast = list(checkbox = castLabel))`

One of the advantages to upgrading to 2.8.3 is the package includes a few vignettes that may be helpful in transitioning your code to exportRecordsTyped.

**Comment by jjdeclercq** [comment] 2023-12-17 15:49
@nutterb Thanks for looking into this.

Updating to 2.8.3 resulted in the same error. Is there something else you wanted me to try?

**Comment by nutterb** [comment] 2023-12-17 16:22
Whoops. There was, and I didn't leave you the code. 

Try

```
X <- makeApiCall(anticancer_key,
    body = list(content = "record",
                      action= "export",
                      format = "csv",
                      returnFormat = "csv")

trimws(as.character(X))
````

Hopefully this returns a character string.

**Comment by jjdeclercq** [comment] 2023-12-17 16:27
`trimws(as.character(X))` resulted in `NA`

`X` prints the following:

```
Response [https://redcap.vanderbilt.edu/api/]
  Date: 2023-12-17 16:24
  Status: 200
  Content-Type: text/csv; charset=utf-8
  Size: 66.9 kB
```

**Comment by nutterb** [comment] 2023-12-17 17:35
Welp! That's exactly the thing I was hoping it wouldn't be.

It seems that something in your project is preventing the server from sending data to the client. Isolating this may not be pretty.

Some things to check before we dig into the records

1. Does `exportProjectInformation(anticancer_key)` provide results?
2. Does `exportMetaData(anticancer_key)` provide results. 

If both of those are giving you the expected returns, we can start trying to isolate what in the data might be problematic. 

You can try things like

exportRecordsTyped(anticancer_key, fields = "record_id", records = "1")

(I'm assuming your ID field is "record_id" and you have auto numbering enabled). I would expect that something this limited might produce a result. 

Hopefully, you can isolate a field that produces the error. If you're comfortable writing nested for loops, you could systematically search for a failure point.

**Comment by jjdeclercq** [comment] 2023-12-17 20:03
I'm definitely getting some strange behavior here. Suggestions 1 and 2 worked as expected. I ran a loop through the list of field names from the metadata and encountered issues with three variables. `c('exclude', "cci", "not_started_dose")` I'm getting two different errors. `'exclude' and "cci"` give the following:

```
exportRecordsTyped(anticancer_key, fields = "exclude", records = IDs[1])
exportRecordsTyped(anticancer_key, fields = "cci", records = IDs[1])

Error in exportRecordsTyped(anticancer_key, fields = "cci", records = IDs[1]) : 
  1 assertions failed:
 * Variable 'fields': Must be a subset of
 * {'record_id','mrn','pt_name','med_name' [[truncated list of all fields in data]]

```

Exporting the data to a csv file from redcap yields a dataset without either `cci` or `exclude`, however both variables are in the codebook.

![image](https://github.com/vubiostat/redcapAPI/assets/13262956/92ccb469-275a-4080-91a1-d5d0e79c63a2)
![image](https://github.com/vubiostat/redcapAPI/assets/13262956/9f4d767f-e355-4585-b722-d5b455de3232)

The good news is that they're both descriptive fields, so I don't need them for analysis.



`exportRecordsTyped(anticancer_key, fields = "not_started_dose", records =IDs[i])` breaks down at record 21.  This gives the error: 

```
Error in if (trimws(as.character(response)) == "") { : 
  missing value where TRUE/FALSE needed
```
This one is strange, because when I export the data directly from redcap to a csv file, there is some free text in that field. However, when I examine the data in the redcap instrument, there is nothing written and no history of any data being entered.

Running `exportRecordsTyped` on the subset of field names without those three variables returns the entire data as expected.

**Comment by nutterb** [comment] 2023-12-17 20:41
These are very informative results. 

Regarding your descriptive fields, I believe the only way to promote that error is to explicitly request the field. exportRecordsTyped will remove them by default, so I don't think we need to do anything special for those.

not_started_dose seems like the culprit. I would guess that there is some kind of multibyte character in the field that shouldn't be there. I don't know if deleting the value and then re-inputting it would clear it (and should only be tried if doing so doesn't violate data integrity rules for the project). @spgarbet, I think I better turn this over to you at this point.

End result: this seems to be something specific to the project and I don't believe anything needs to be done within `redcapAPI`

**Comment by spgarbet** [comment] 2023-12-18 14:17
I saw something like this is the past few days. What turned out to be the problem was the metadata in the field_label field had a lot of HTML. This was fine, but right in the middle the string of html was corrupted and wasn't UTF8. It just had random raw bytes in it. The person I was working with fixed it before I could test further and capture as a possible failure mode to deal with. I was going to open a ticket this week, but I suspect this is the same thing. 

I suspect that it's a latin encoding and related to this: https://stackoverflow.com/questions/17291287/how-to-identify-delete-non-utf-8-characters-in-r

**Comment by jjdeclercq** [comment] 2023-12-18 14:35
Thanks for the help in getting this figured out @nutterb !!

@spgarbet , I think the offending character is here: `Iíve`. Is there any other information that I can provide you?

**Comment by spgarbet** [comment] 2023-12-18 16:06
I would love to see an exact example of an offending character and where it existed. Then we put it in our sandbox project and see if we can find a workaround.

**Comment by spgarbet** [comment] 2023-12-18 17:30
Setting the encoding to latin1 for the read works. 

```
x <- "fa\xE7ile"
Encoding(x) <- "UTF-8"
data <- read.csv(con <- textConnection(x), encoding="latin1")
close(con)
```

**Comment by nutterb** [comment] 2023-12-22 14:11
This makes me wonder if using the `config` argument might work.

```
exportRecordsTyped(rcon, config = list(encoding = "latin1")
`

It would be really cool if it did :)

**Comment by spgarbet** [comment] 2023-12-22 16:22
I think the issue here is the headers for the csv are latin1 and the data is utf-8. I am seeing this with projects created under 14.0.2 using Windows. I don't know what 14.0.3 will bring. The right answer might be we don't fix it all as it is corrupted data being reported, but this pops up from time to time. I've been trying to track down what causes it and finally saw an example before it was fixed. It'd be nice if the library could handle it gracefully, but it is corrupt headers.

**Comment by nutterb** [comment] 2024-01-18 15:47
> I have gone into our sandbox project and tried to break it and cannot get the interface to accept non UTF8 characters. I don't know how to recreate this weird issue.

1. How old is the project in which the problem exists?
2. In examples you've seen, is it likely to be a copy/paste issue...copying weird characters from a Word file, perhaps?
3. Have we tried uploading characters through the data dictionary import tool?

**Comment by spgarbet** [comment] 2024-01-18 16:00
I'm working on #1 and #2. Trying to find out more. #3 I have not.

**Comment by spgarbet** [comment] 2024-01-18 19:42
1. This one August 22, 2023. 
2. It's a free text field that is empty on the GUI (i.e. it hits an error and reports a blank field). When exporting it shows up with weird characters. But when using the API it has invalid characters.

**Comment by spgarbet** [comment] 2024-01-18 19:45
I attempted to reproduce this and the current REDCap interface correctly handles it from Linux/Firefox. It converts it to UTF-8 and everything is fine.

**Comment by spgarbet** [comment] 2024-01-24 23:25
@jjdeclercq Can you install 2.8.4 devtools::install_github("vubiostat/redcapAPI") and see if this fixes your issue?

**Comment by jjdeclercq** [comment] 2024-01-29 15:25
@spgarbet Updated to 2.8.4, but I'm still getting the same error

**Comment by spgarbet** [comment] 2024-01-29 15:57
> sigh < Back to the grindstone.

**Comment by spgarbet** [comment] 2024-01-30 13:51
@jjdeclercq  If you would be so kind as to try the branch (not merged yet) 
`devtools::install_github("vubiostat/redcapAPI[iconv-290-297-314]")

The magic formula to fix the problem for good in one pass is as follows:

1. Inform the project's owner what is about to be done and get their permission.
2. Use the GUI interface and export the meta data.
3. Run a script to transcode it.
```
fileName <- '<YOUR_METADATA_FILE_NAME>.csv'
raw <- readr::read_file_raw(fileName)
fixed <- iconv(rawToChar(raw), from='latin1', to='utf8', '\u25a1')

if(any(grepl("\u25a1", fixed))) stop("Latin encoding did NOT work")

cat(fixed, file="<YOUR_METADATA_FILE_NAME>-FIXED-UTF8.csv")
```
4. Make sure the stop error didn't trigger and inspect the resulting file to make sure it looks right and the characters are converted fine. 
5. Refresh the metadata for the project. If it's a production project one has to contact the admin support team for REDCap at your institution.

**Comment by jjdeclercq** [comment] 2024-01-30 16:35
@spgarbet Still waiting on consent from the project owner, but I got this error in installing the new version: 

`Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`vubiostat`) and repo name (`redcapAPI[iconv-290-297-314]`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.`

**Comment by spgarbet** [comment] 2024-01-30 16:44
They changed the syntax.

`devtools::install_github("vubiostat/redcapAPI", ref="iconv-290-297-314")`

**Comment by spgarbet** [comment] 2024-01-30 21:07
Reported to still be having the same error.

**Comment by spgarbet** [comment] 2024-01-30 23:27
Now it's reported to be working.

**Closed by spgarbet** 2024-01-30 23:27 UTC
Labels: bug
