### ISSUE TITLE
Illegal data dictionaries

### ISSUE THREAD

**Issue by berryld1** [vubiostat/redcapAPI#327] opened 2024-02-05 17:46 UTC
(Hmm, the HTML tags disappear...)
Hey! Me again.

I know we've covered this in various fashions - the issue of illegal characters in data dictionaries, which results in a metadata export of "NA", which then makes it impossible to import or export any data (no fields are recognized as being valid fields).

Two of my projects that run automated ETL scripts broke this morning - and I think must be due to a dd update that introduced illegal characters, because when I run locally, I get "NA" data dictionary out.

I did not design nor do I maintain these redcaps, so, at the mercy of the client as far as that's concerned.

For both of the projects that broke, I ran them through cleanseMetaData() to get the clean DD, then diffed that with the original DD to find which fields R changed.

In one project, just one field.

In the other project, nearly 100 fields.

I'm sending these back to the client to fix, but hoped you guys might have some guidance.

The common theme always seems to be HTML tags and a space.

So, the "dirty" dd will have something like:

(I don't know how to make the HTML tags not disappear, so I'm going to us 
left sideways carat = (
right sideways carat = )
"blah-blah (p) (/p) blah-blah"

, and the corresponding clean dd will be:

"blah blah (p)(/p) blah-blah"

So, the only change is closing that space between (p) and (/p)

So, that's pretty horrible to have to review and fix, ESPECIALLY because you can't always just close the space, for example:

"you must (em)always)(/em)", and R wants to do:

"you must(em)always(/em)".

With that background, finally, my question:
Do you think this is maybe non-breaking white space that R doesn't like?
Or, if not, what? A legit space does not seem like it should wreak so much havoc.
Any suggestions for how to avoid? 
Would R be happier (or less happy) with 
& n b s p ;<

so, the non-breaking white space (if that's what it is) is just some characters vs. some weird non-character thing invisible to the naked eye?

**Comment by couthcommander** [comment] 2024-02-06 17:20
You can type less than (&lt;) or greater than (&gt;) by typing ampersand followed by "lt;" or "gt;".

My guess is the "space" is not a space, and you'd need to ask the client what they intended for the ~100 fields.

I'm not sure what you mean by R wants to do "you must&lt;em&gt;always&lt;/em&gt;". Are you writing code that converts the original to that? We might be able to find a regular expression that would work, though I still suspect you don't actually want to just remove the "space".

**Comment by berryld1** [comment] 2024-02-06 19:22
Thanks, Cole.

Wow, sometimes I'm just astonished / appalled at how my brain works in silos. I suddenly don't know the name for "greater than" / "less than" symbols because in the context of an HTML tag. 

Anyhow! Let me try to clarify.

When data dictionaries have characters in them that R doesn't like, the data dictionary export fails, and you get something like this:
![image](https://github.com/vubiostat/redcapAPI/assets/116016336/62b838eb-a99a-496c-a4ea-8eb07b65d9b2)

This is true whether you use exportMetaData() or what the redcapConnection gets out and caches:
![image](https://github.com/vubiostat/redcapAPI/assets/116016336/2de3d0b1-63d6-4389-8431-1a46670559b3)

The practical consequence of this is that redcapAPI is now dead in the water - absolutely everything it does validates through the metadata, so if you can't get the metadata out, you can't do anything.

To find what R / redcapAPI doesn't like, you can pull the DD via the GUI and run cleanse_metadata(). I have this pipelined in a script to then diff the cleaned against the dirty. And these are the sorts of differences I see:
oh! here's one that doesn't involve an html tag at all:
![image](https://github.com/vubiostat/redcapAPI/assets/116016336/1d936190-b9d5-4f7f-be61-9e594674ba3f)

here's more the thing I typically see:
![image](https://github.com/vubiostat/redcapAPI/assets/116016336/2ab498e0-9df2-4f8a-81a3-3a347c2fa58c)

So, for real, no, there's not supposed to be anything here but for the space - but something happens somewhere between Excel (dd) - redcap - redcapAPI/R - where an innocent space becomes a character that is:
- invisible to the naked eye
- breaks redcapAPI
- can not be addressed simply by running the dd through cleanseMetaData() because in many cases, a real honest-to-goodness space *should* be there

I should further add - this is NOT happening in the redcap API (the API). If I run the call in the API playground, I get the DD out. And there you can see the characters that are probably causing the problem, which redcap renders as diamond-?:
![image](https://github.com/vubiostat/redcapAPI/assets/116016336/835c9faf-346e-42da-80d5-0ed2e914260e)

The same thing happens sometimes with data - I'm sometimes unable to get some records out using exportRecordsTyped(), but if I write the API call natively, I can get the record out.

So, when redcapAPI (the R package) hits these characters in any context, it just craps out - which, my understanding from Shawn is that's because R doesn't know how to handle them. So, when I say "what R wants to do", what I really mean is, what cleanseMetaData() wants to do to make R happy. 

Here's a good example where you can see it's unlikely this illegal character is intended to mean anything - the dd designers just want a space there. Which is why I say there seems to be part of this that's an Excel - redcap thing - somehow, a dd submitted with an innocent space, redcap interprets as uninterpretable, and then passes that problem along to R. 
![image](https://github.com/vubiostat/redcapAPI/assets/116016336/7433f5af-a05b-4531-949e-3f5b3e35a23b)

But we can't control the Excel-redcap side of things. And if we tell redcap we can't get these dds or records out, they'll say, *we* can, because you can, if you write the call natively. You can't with redcapAPI package because there's a lot more stuff going on there, where R actually has to handle the data/metadata, and refuses to do it with illegal characters.

Does that help?

I know I keep asking this question in different ways and different contexts - because I keep running into it. 

And I'm not sure it's a practical answer for me to send a diff file of 100 fields to the client and say - "figure out how to make this not have illegal characters!" 

@spgarbet - would it be possible to have cleanseMetaData replace an illegal character with a space, instead of empty string? Not sure if redcap would turn right around and make it back into an illegal character, that part is utterly mysterious. 

oh! It suddenly occurs to me - likely, a lot of these fields are originally built in the designer, in "rich html" mode, and that's what creates these weirdnesses, vs. a space in an excel file suddenly turning into a computing pariah. I don't know, I guess.

**Comment by couthcommander** [comment] 2024-02-06 19:44
Perfect, thank you for clarifying. You sound spot on, this is likely a consequence of using the designer, the intention is that this should be a space, and `cleanseMetaData` should handle this better.

**Comment by spgarbet** [comment] 2024-02-06 20:05
Is this with version 2.8.4? The new version should be filtering those out cleanly.

**Comment by berryld1** [comment] 2024-02-06 20:08
Yes, 2.8.4

"Filtering those out cleanly" = filtering what out?

**Comment by spgarbet** [comment] 2024-02-06 20:21
The weird characters. They should come over in the meta data without issue. 

I'm trying the copy you gave me and having no issues with exporting.

**Comment by spgarbet** [comment] 2024-02-06 20:27
You were installing direct via devtools::install_github. I think you have an interim version before all the bugs were ironed out. Could you do me a favor and reinstall? The current version on CRAN is the latest.

**Comment by berryld1** [comment] 2024-02-06 20:36
Yes, I will reinstall. 
However, this complicates assessment of the issue:
![image](https://github.com/vubiostat/redcapAPI/assets/116016336/0a58c8c8-897b-4b5e-bb47-8af7604ed49b)

![image](https://github.com/vubiostat/redcapAPI/assets/116016336/8f6467b5-f994-499c-929a-ae4f6049285a)

In other words - I, too, can get the DD out of the dev copy. I've now downloaded-uploaded PROD to DEV three times to make sure I didn't accidentally load back the DEV dd or forget to click "Commit" or whatever. Same result each time.

Which makes the solution for Anne (possibly) simple - download-upload the DD (??)

But makes testing difficult because I can't give you access to PROD. Anne is very strict about this.

**Comment by berryld1** [comment] 2024-02-06 20:40
Hmm, usually it tells me "MD5 sums checked and downloaded binary packages blah-blah" or something like that:
![image](https://github.com/vubiostat/redcapAPI/assets/116016336/7b48465e-7b1d-4ec2-a49c-cc60a1e19d8b)

I ran it again just to be sure.

Does it mean there was nothing to update?

**Comment by couthcommander** [comment] 2024-02-06 20:46
Go ahead and use `install.packages('redcapAPI')` instead

**Comment by berryld1** [comment] 2024-02-06 20:52
BINGO!

![image](https://github.com/vubiostat/redcapAPI/assets/116016336/e0efa732-a180-4b56-bfd4-86f10eaf11ae)

![image](https://github.com/vubiostat/redcapAPI/assets/116016336/05eb507e-8922-46d0-8019-04f3ee0a78bb)

Thanks, Shawn and Cole!!!

**Comment by spgarbet** [comment] 2024-02-06 21:09
Duplicate of #290

**Closed** 2024-02-06 21:13 UTC
Labels: duplicate
